jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: SonarQubePreBuild@1
    displayName: 'Prepare analysis on SonarCloud'
    inputs:
      connectedServiceName: SonarCloud-Generic
      projectKey: kbrons_PWABuilder
      projectName: PWABuilder
      projectVersion: 1.0

  - bash: docker build --target $(targetName) -t manifoldsite . 
    displayName: 'Build docker image'

  - task: SonarQubePostTest@1
    continueOnError: true
    timeoutInMinutes: 2
