jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:

  - bash: docker build --target $(targetName) -t manifoldsite . 
    displayName: 'Build docker image'
  
  - bash: npm install -g sonarqube-scanner
    displayName: 'Install sonarqube-scanner from npm'
  
  - bash: sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$(sonar-login) -Dsonar.projectKey=kbrons_PWABuilder -Dsonar.sources=.