jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:

  - bash: docker build --target $(targetName) -t manifoldsite . 
    displayName: 'Build docker image'
  
  - bash: npm install sonarqube-scanner
    displayName: 'Install sonarqube-scanner from npm'

  - bash: ./node_modules/sonarqube-scanner/dist/bin/sonar-scanner -D sonar.host.url=https://sonarcloud.io -D sonar.projectKey="$(sonar-projectKey)" -D sonar.organization="$(sonar-organization)" -D sonar.login="$(sonar-login)" -D sonar.sources="."